### ISSUE TITLE
怎么指定某个队下载？

### ISSUE THREAD

**Issue by kybom** [SNH48Live/KVM48#1]
现在只能指定成员，可否指定某个队或某个团下载，比如指定SII，下载SII所有成员的视频。

**Comment by zmwangx** [comment]
README:

> Here is a sample configuration for downloading the VODs of Team SⅡ members daily:
>
> ```
> # SNH48
> group_id: 10
> # Team SⅡ members
> names:
> - 陈观慧
> - 陈思
> - 成珏
> - 戴萌
> - 蒋芸
> - 孔肖吟
> - 李宇琪
> - 刘增艳
> - 吕一
> - 莫寒
> ...
> ```

目前下载一个队的成员需要把所有成员的名字列出来。

https://plive.48.cn/livesystem/api/live/v1/memberLivePage endpoint本身是没有队伍的概念的。理论上我可以包括各队成员的数据，但是这样不但时有数据更新（即使我更新了估计用户也不会及时更新），而且关于队伍的成员也会有一定争议，比如成珏、潘燕琦、温晶婕算S队的吗？弊大于利，还是自己列成员、需要的时候自己更新成员列表吧。

https://plive.48.cn/livesystem/api/live/v1/memberLivePage endpoint倒是有团的概念，但我很难想象哪个人需要下全团的。没有这种需求的情况下不想把代码和配置搞复杂，何况现在已经可以下全团了，只要多列人就行。

关了，但还有问题可以接着提。

**Comment by loony175** [comment]
<https://github.com/loony175/PocketPC/blob/master/pocket.py#L110-L111>
可以从另一API获取，缺点是成员的归属以官方为准
