### ISSUE TITLE
new group structure is coming...

### ISSUE THREAD

**Issue by xyleey** [SNH48Live/KVM48#8]
Well, due to re-structure of the group today, significant changes occur mainly in member lists. I know you are busy but I'm just thinking about this tool itself, need update something or not (not in rush). I had shared this tool to many other fans however I do not know how many of them still use it. So.. up to you really. 
I'm working on the channel though. And regards to you.

**Comment by zmwangx** [comment]
Thanks for the reminder.

I don't hard code or download any member list; see #1. In the default configuration, `group_id` is 0, so the entire group is crawled. One may set `group_id` to 10, 11 or 12 (I guess 13 and 14 will be shuttered?) to limit the scope, but that's the highest granularity, and that's entirely the user's decision.

I don't see any change in the API, so things should continue to work normally. There's also a daily Travis job to ensure this. But I can leave this open for a few days just in case.

**Comment by xyleey** [comment]
Surprise for immediate reply. Facepalm.
Yeah I'm considering need more manual listing in config.yml further as well, to amend the member list under group_id equals to 0.

**Comment by xyleey** [comment]
> Thanks for the reminder.
> 
> I don't hard code or download any member list; see #1. In the default configuration, `group_id` is 0, so the entire group is crawled. One may set `group_id` to 10, 11 or 12 (I guess 13 and 14 will be shuttered?) to limit the scope, but that's the highest granularity, and that's entirely the user's decision.
> 
> I don't see any change in the API, so things should continue to work normally. There's also a daily Travis job to ensure this. But I can leave this open for a few days just in case.

**Comment by xyleey** [comment]
Sorry for mistake and press the close button...facepalm.
Yeah I'm considering need more manual listing in config.yml further as well, to amend the member list under group_id equals to 0. Thanks.

**Comment by zmwangx** [comment]
No problem. In fact, a `group_id` of 0 includes every single member — past, present, or future — in all groups. Unless someone you follow has been reassigned to another group, you don't need to change `_config.yml` a bit.

**Comment by zmwangx** [comment]
> Unless someone you follow has been reassigned to another group, you don't need to change _config.yml a bit.

To expand on that, even if someone you follow has been reassigned, you don't need to update `_config.yml` unless you set `group_id` to something nonzero.

**Comment by zmwangx** [comment]
Closing as I didn't notice any disruption.
